### ISSUE TITLE
Cleanup/prepare repo and improve README

### ISSUE THREAD

**Issue by omarcostahamido** [omarcostahamido/PVM#2]
Get repo ready/easier for MSWE team to start working.

**TODO**
- [x] add @KaneBetter @rustberry @SSSSam141 and @xrk-git as repository collaborators.
- [x] remove `Todo` section on the [README.md](../)
- [x] add table with repo contents overview
- [x] add instructions for running the control patch on the `Running` section
- [x] create first issue to add start position offset parameter
- [x] create issue draft for i) tearing ii) going out of sync
