### ISSUE TITLE
Readme updates part 2

### ISSUE THREAD

**Issue by omarcostahamido** [omarcostahamido/PVM#70]
since I will be closing #57 with #62 before 2 of the sub-items are cleared, I am copying them here to be tackled later:

**TODO:**
- [x] review Structure table
- [x] review and complete wiki pages
- [x] add hyperlinks to sections on mermaid overview?

**Comment by omarcostahamido** [comment]
these things, once solved, will finally allow the deployment of v0.5.0 release

**Comment by omarcostahamido** [comment]
@gggfffsss 
FYI, just completed several revisions on the wiki, including just writing all the [example descriptions](https://github.com/omarcostahamido/PVM/wiki/Examples)... a great exercise to do, for someone who would need to learn how this works...
