### ISSUE TITLE
The Path to v0.6

### ISSUE THREAD

**Issue by omarcostahamido** [omarcostahamido/PVM#71]
**TODO:**
- [ ] #72
- [ ] #73
- [ ] #74
- [ ] #75
- [ ] #78
- [ ] #80
- [ ] #79
- [ ] #76
- [ ] #77
- [ ] #82

**Comment by omarcostahamido** [comment]
@gggfffsss what am i forgetting?

**Comment by gggfffsss** [comment]
@omarcostahamido here is what I am thinking for now, I'm sure more will come up. I am finishing the first task on my list below today, finally.

- [ ] update pitch video (Grant)
- [ ] fix/ update HDMI port selection (default to active HDMI port? Select port in Max?)
- [ ] test and implement dual HDMI video output (two video channels from one device)
- [ ] Android implementation?
- [ ] Autostart PVM option

**Comment by omarcostahamido** [comment]
@gggfffsss 
>fix/ update HDMI port selection (default to active HDMI port? Select port in Max?)

As far as I am aware I don't think there is a way to detect the active port. However, that's a very interesting idea to be able to select it from Max!
I can only agree that testing is necessary.
The android implementation is really tempting... I am wondering if it will be worth creating a separate repo "AVM" (Android Video Machine) or if we can generalize the project just well enough so that it is a single repo project with compilations to multiple platforms. So we could keep `PVM` as in `Portable Video Machine` haha. But seriously, I am afraid the android implementation will be so different, in what the code looks like, that it may require a complete different code structure even.
**edit:** well at least I opened [the space](https://github.com/omarcostahamido/AVM) for it.
And Yes, to the autostart!

**Comment by omarcostahamido** [comment]
@gggfffsss 

>  test and implement dual HDMI video output (two video channels from one device)

What do you mean here when you say `implement dual HDMI video output`?
It should be done already... but more testing is always good, yes.

**edit:** added this on #78 , a battery of tests to be done! It will be important to know what is working, what is not, what needs to be improved, more well documented, and what not.

**Comment by omarcostahamido** [comment]
sorry missclicked on closing the issue.
I've just finished updating the OP, and created some issue from this listing

**Comment by omarcostahamido** [comment]
@gggfffsss 
I was looking into something else and found this [SyncPlay](https://syncplay.pl/). Maybe not helpful for everything that we want to achieve here, but maybe good to know about it.
