### ISSUE TITLE
Tests for v0.6

### ISSUE THREAD

**Issue by omarcostahamido** [omarcostahamido/PVM#78]
**TODO:**
- [ ] test and implement dual HDMI video output (two video channels from one device)
- [ ] test performance between different compatible/working video file formats. 
- [ ] test and discover incompatible file types/codecs. For example `prores422`, as noted in #73, seems to not be compatible with omx.
- [ ] test SSH connection. See our guide [here](https://github.com/omarcostahamido/PVM/wiki/VS-Code-ssh-to-Raspberry-Pi) and complete any missing steps. (for reference, [this other page](https://github.com/omarcostahamido/PVM/wiki/How-to-connect-to-a-Raspberry-Pi-remotely#the-command-line-way-ssh), mentioned some other instructions for getting started with SSH)

**Comment by omarcostahamido** [comment]
[This section](https://github.com/omarcostahamido/PVM#videos) will need to be updated accordingly.

**Comment by omarcostahamido** [comment]
Will need to also update this [google doc](https://docs.google.com/document/d/e/2PACX-1vTolcNXYD1-h9kRoOviPFZkdQkjLcTRg0mUuQMUqvTpBXXib2JJWfdv-XmTqWGt1egi3FdDRSDbz97O/pub) and/or, better yet, find an alternative way to distribute/share the example videos.
**edit:** the sample video file has now been included with the `v0.5.0` release: https://github.com/omarcostahamido/PVM/releases/download/v0.5.0-beta/pattern01_h264.mov
